version: "3.9"

services:
  go-db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  go-app:
    container_name: go-app
    build: .
    image: go-api-tutorial
    depends_on:
      - go-db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=go-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=postgres

volumes:
  pgdata: {}
